SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[testtable](
	[TestID] [int] NOT NULL,
	[RecordID] [int] NOT NULL,
	[VariableID] [int] NOT NULL,
	[Data] [nvarchar](2000) NULL,
	[DataDictEntryID] [int] NULL
 CONSTRAINT [PK_DataPoints] PRIMARY KEY CLUSTERED 
(
	[TestID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO


